"""content_hash unique per company not global

Revision ID: 8e4427050247
Revises: 89a2f4e7b32c
Create Date: 2026-05-24 21:56:44.175835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4427050247'
down_revision: Union[str, Sequence[str], None] = '89a2f4e7b32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_content_hash'), table_name='reviews')
    op.create_index(op.f('ix_reviews_content_hash'), 'reviews', ['content_hash'], unique=False)
    op.create_unique_constraint('uq_review_company_hash', 'reviews', ['company_id', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_company_hash', 'reviews', type_='unique')
    op.drop_index(op.f('ix_reviews_content_hash'), table_name='reviews')
    op.create_index(op.f('ix_reviews_content_hash'), 'reviews', ['content_hash'], unique=True)
    # ### end Alembic commands ###
